org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neoforge_version=21.1.194

mod_id=reliquified_artifacts
mod_name=reliquified_artifacts

mod_version=1.0.8

mod_group_id=it.hurts.shatterbyte.reliquified_artifacts

mod_authors=Octo-Studios

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
