modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
issueTrackerURL = "https://discord.gg/pHren9yxzW"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/rar-compat"
authors = "${mod_authors}"
description = '''Compat addon between Relics and Artifacts'''

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "curios"
type="required"
mandatory = true
versionRange = "[5.2.0+1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "octolib"
type="required"
mandatory = true
versionRange = "[0.3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "artifacts"
type="required"
mandatory = true
versionRange = "[9.5.13,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "relics"
type="required"
mandatory = true
versionRange = "[0.8.0.7,)"
ordering = "NONE"
side = "BOTH"